// components/resume/PdfDownloader.vue
<template>
  <b-button variant="primary" size="sm" :href="file" target="_blank" download="LOUVET_Celine.pdf"
    ><b-icon-file-earmark-pdf-fill class="icon icon-pdf" /> <span>PDF</span></b-button
  >
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";

@Component
export default class PdfDownloader extends Vue {
  get file() {
    const root = "https://storage.googleapis.com/celinelouvet-cv.appspot.com/resume";

    return `${root}/LOUVET_Celine_${this.$i18n.locale.toUpperCase()}.pdf`;
  }
}
</script>

<style scoped>
.icon-pdf {
  font-size: 0.9em !important;
  vertical-align: middle !important;
}
</style>

// src/components/features/resume/parts/pdfDownloader/PdfDownloader.tsx
import { Button, Link, Tooltip } from '@chakra-ui/react';
import { type FC } from 'react';
import { useTranslation } from 'react-i18next';
import { BsFileEarmarkPdfFill } from 'react-icons/bs';

const root =
  'https://storage.googleapis.com/celinelouvet-cv.appspot.com/resume';

export const PdfDownloader: FC = () => {
  const { i18n } = useTranslation();

  const file = `${root}/LOUVET_Celine_${i18n.language.toUpperCase()}.pdf`;
  const fileName = 'LOUVET_Celine.pdf';
  return (
    <Link href={file} download={fileName} isExternal>
      <Tooltip label="Download PDF">
        <Button leftIcon={<BsFileEarmarkPdfFill />} size="sm">
          PDF
        </Button>
      </Tooltip>
    </Link>
  );
};
