// components/resume/summary/Picture.vue
<template>
  <div>
    <div class="d-flex flex-row justify-content-center">
      <b-avatar src="~/assets/square-gray.png" class="photo" aria-label="photo"></b-avatar>
    </div>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";

@Component
export default class Picture extends Vue {}
</script>

<style>
.photo {
  width: var(--photo-size);
  height: var(--photo-size);
  border: 3px solid #fff;
}
</style>

// src/components/core/media/picture/Picture.tsx
import {
  Avatar as ChakraAvatar,
  type AvatarProps as ChakraAvatarProps,
  type StyleConfig,
  forwardRef,
  useStyleConfig,
} from '@chakra-ui/react';

export type PictureProps = Omit<ChakraAvatarProps, 'src'>;

export const Picture = forwardRef<PictureProps, 'img'>(
  ({ size, ...props }, ref) => {
    const styles = useStyleConfig('Picture', { size });

    return (
      <ChakraAvatar src="./square-gray.png" sx={styles} {...props} ref={ref} />
    );
  }
);

export const pictureInPx = 200;

export const pictureStyles = {
  baseStyle: {
    width: `${pictureInPx}px`,
    height: `${pictureInPx}px`,
    border: '3px solid white',
  },
  sizes: {
    md: {
      width: `${pictureInPx / 2}px`,
      height: `${pictureInPx / 2}px`,
    },
    lg: {
      width: `${pictureInPx}px`,
      height: `${pictureInPx}px`,
    },
  },
  defaultProps: {
    size: 'md',
  },
} satisfies StyleConfig;
